title: Home
views:
- badges: []
  cards:
  - entity: weather.forecast_home
    show_forecast: false
    type: weather-forecast
  - cards:
    - entities:
      - entity: lock.front_door
        name: Lock
      - entity: sensor.front_door_battery
        name: Battery
      title: Front Door
      type: entities
    columns: 1
    square: false
    type: grid
  - entities:
    - entity: lock.powder_room_door
      name: Door
    - entity: sensor.powder_room_door_battery
    title: Powder Room
    type: entities
  - entities:
    - switch.projector
    type: entities
  - entities:
    - name: Open Screen
      tap_action:
        action: call-service
        service: rest_command.open_screen
      type: button
    - name: Close Screen
      tap_action:
        action: call-service
        service: rest_command.close_screen
      type: button
    show_header_toggle: false
    title: Projector Screen
    type: entities
  - entity: light.downstairs_lights
    type: light
  - entities:
    - cover.shade_1
    - cover.shade_2
    - cover.shade_3
    - cover.shade_4
    - cover.shade_5
    type: entities
  - area: back_yard
    camera_view: live
    show_camera: true
    type: area
  - area: front_door
    camera_view: live
    show_camera: true
    type: area
  - area: patio
    camera_view: live
    show_camera: true
    type: area
  - area: side_door
    camera_view: live
    show_camera: true
    type: area
  - area: carport
    camera_view: live
    show_camera: true
    type: area
  - entity: media_player.kitchen_speaker
    type: media-control
  - cards:
    - entity: media_player.balcony
      type: media-control
    - entity: media_player.living_room
      type: media-control
    - entity: media_player.main_bedroom
      type: media-control
    - entity: media_player.office
      type: media-control
    - entity: media_player.patio
      type: media-control
    - entity: media_player.onkyo_tx_nr696_621fad
      type: media-control
    columns: 1
    square: false
    type: grid
  - entity: media_player.living_room_2
    type: media-control
  - entity: light.entry_front_porch
    type: light
  icon: mdi:home
  path: default_view
  title: Pride Rock Rawr
  type: masonry
